---
- hosts: all

  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ curdir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - file:
        src: "{{ curdir }}/files/coc-settings.json"
        dest: ~/.config/nvim/coc-settings.json
        state: link

