[settings]
minimum_release_age_excludes = ["claude-code", "opencode", "codex"]

[tools]
node = "24.15.0"
ruby = "4.0.2"
python = "3.14.6"
erlang = "29.0.2"
elixir = "1.20.1"
opencode = "latest"
claude-code = "latest"
codex = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
lazygit = "latest"
lazyssh = "latest"
