export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export EDITOR="nvim"
export TERM="xterm-256color"

export BAT_THEME="Catppuccin Mocha"

[ -f ~/.aliases ]     && source ~/.aliases
[ -f ~/.my_aliases ]  && source ~/.my_aliases

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
  git
  git-flow-avh
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source "$ZSH/oh-my-zsh.sh"

# mise
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

HYPHEN_INSENSITIVE="true"

# Uncomment to enable correction (optional)
# ENABLE_CORRECTION="true"

# Uncomment to show completion dots (optional)
# COMPLETION_WAITING_DOTS="true"

# fzf (Fuzzy finder)
if [[ "$OSTYPE" == "darwin"* ]]; then
  [ -r "/opt/homebrew/opt/fzf/shell/key-bindings.zsh" ] && source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"
  [ -r "/opt/homebrew/opt/fzf/shell/completion.zsh" ] && source "/opt/homebrew/opt/fzf/shell/completion.zsh"
else
  [ -r "/usr/share/fzf/key-bindings.zsh" ] && source "/usr/share/fzf/key-bindings.zsh"
  [ -r "/usr/share/fzf/completion.zsh" ] && source "/usr/share/fzf/completion.zsh"
fi

# add to PATH Go-based packages
if command -v go >/dev/null 2>&1; then
  export PATH="$(go env GOBIN || echo $HOME/go/bin):$PATH"
fi

# Created for php 8.3 setup
export ICU_CXXFLAGS="-std=c++17"
export PATH="/opt/homebrew/opt/php@8.3/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.3/sbin:$PATH"
